### ISSUE TITLE
How to add  custom fields when creating posts?

### ISSUE THREAD

**Issue by Leeiio** [WP-API/node-wpapi#333] opened 2017-08-22 06:37 UTC
I didn't see how in the API docs.

**Comment by dimadin** [comment] 2017-10-25 13:35
Read my comment at [#280](https://github.com/WP-API/node-wpapi/issues/280#issuecomment-339329973).

**Comment by kadamwhite** [comment] 2019-10-21 21:36
Closing as a duplicate of #280

**Closed by kadamwhite** 2019-10-21 21:36 UTC
