### ISSUE TITLE
_paging.links empty?

### ISSUE THREAD

**Issue by greypiglet** [WP-API/node-wpapi#332] opened 2017-07-28 15:15 UTC
Having an issue where a basic request as below:
``` javascript
 wp.posts().perPage(2)
  .then((data) => {
    console.log(data)
  }
```
isn't returning a populated links object. The `total` and `totalPages` are coming in as expected but `links` is empty.

``` javascript
data = [
  { post },
  { post },
  _paging: {
    links: {},
    total: "26",
    totalPages: "13"
}]
```

Running WordPress 4.8 and node-wpapi 1.1.2.

**Comment by nikosolihin** [comment] 2017-12-29 06:51
I'm experiencing this too. Have you been able to solve it @warrenkeith?

**Comment by warrenkeith** [comment] 2017-12-29 13:40
@nikosolihin Nope afraid not! Project took a different direction so was moved off WordPress unfortunately.

**Comment by whiteseagull** [comment] 2018-08-20 12:41
I have this issue too, so I'm unable to use the getAll functions reported in https://github.com/WP-API/node-wpapi. How can I do to fetch all the posts?
wpapi 1.1.2, WordPress 4.9, the "rel next" link is returned as an header

**Comment by computamike** [comment] 2018-10-17 13:50
I am experiencing this issue - here's what I have found : 

Here is a trace of the response coming back from wordpress
![image](https://user-images.githubusercontent.com/464876/47090531-0551d880-d21b-11e8-92f4-aeffd1a0f5c1.png)

The docs say that a collection object should be enriched with a ```_paging``` property
and [http-transport.js](https://github.com/WP-API/node-wpapi/blob/03ad1e3f08a2fe6924c95942a1fa59d2f8823457/lib/http-transport.js) does seem to show a _paging property being set - however it also seems to be checking for headers ```x-wp-totalpages```.  Now I've only just found this but if the header doesn't exist then this returns a null - which may explain why it's not work - I've not confirmed this yet but I imagine this is a case issue.  

Need to confirm with Wordpress docs what headers it should or could be returning.   Have forked and may look at creating a check ignoring case.

**Comment by kadamwhite** [comment] 2018-12-21 19:21
While I do not expect #408 to fully address this issue, I've added some safeguards which may improve things; they will be included in the next released version of the library, as will a change which will use a consistent (and different) library to parse links. I'm going to provisionally close this, and we can revisit after the next release if the issue persists.

**Closed by kadamwhite** 2018-12-21 19:21 UTC
