### ISSUE TITLE
how to consume API from wordpress Public API ?

### ISSUE THREAD

**Issue by yann-yinn** [WP-API/node-wpapi#381] opened 2018-07-06 17:25 UTC
Hello !
First, thanks for this awesome client, which , i love so much the simplicity of it * - *
```javascript
const posts = await wpapi
      .posts()
      .tags(tag.id)
      .perPage(10)
      .embed()
      .page(currentPage);
````

My question : I am working on [Reactpress](https://github.com/nyl-auster/reactpress) and would like to consume a wordpress public api, like this one , for testing purposes :

```
https://public-api.wordpress.com/wp/v2/sites/yinrun.wordpress.com
```

I tried this with no luck
```js
import WPAPI from "wpapi";
import config from "./publicConfig";
export default new WPAPI({
  endpoint: "https://public-api.wordpress.com/wp/v2/sites/yinrun.wordpress.com"
});
```

I know there is a trick with namespace, but it means every request has to be rewritten : https://github.com/WP-API/node-wpapi/issues/329

Any suggestions ?

**Comment by HX-Rd** [comment] 2018-07-15 19:06
Was checking this out my self, I got a response with this
```javascript
var WPAPI = require("wpapi");
var wp = new WPAPI({ endpoint: 'https://public-api.wordpress.com/rest/v1.1' });
wp.posts().namespace('sites/yinrun.wordpress.com').then(function( data ) {
    console.log(data)
}).catch(function( err ) {
    console.log(err)
});
```

**Comment by kadamwhite** [comment] 2019-01-24 19:35
Closing as a duplicate of #329 -- there's no good suggestion currently but I've added documenting or solving this to our 2.0 milestone.

**Closed by kadamwhite** 2019-01-24 19:35 UTC
