### ISSUE TITLE
how to set post_meta when creating a post?

### ISSUE THREAD

**Issue by jiji262** [WP-API/node-wpapi#286] opened 2017-01-17 07:19 UTC

**Comment by emreycolakoglu** [comment] 2017-01-22 18:42
I'd like to learn this as well. Currently I'm trying like
```
meta: [{
            key: 'external_thumbnail',
            value: thumbnail
        }]
```
while creating posts, but no luck

**Comment by chattes** [comment] 2017-03-02 11:25
Even I have the same issue any ideas how can we update Meta Fields?

**Comment by kadamwhite** [comment] 2017-03-03 16:33
How are you registering the meta you wish to update?

**Comment by kadamwhite** [comment] 2017-03-03 16:35
If you use `register_rest_field` like this: https://github.com/kadamwhite/wp-notebook/blob/master/wp-notebook.php#L62-L81 then you should be able to update the value by passing that key in the response: https://github.com/kadamwhite/wp-notebook/blob/master/src/components/EntryComposer/index.jsx#L49-L53

**Comment by kadamwhite** [comment] 2017-03-03 16:36
If you're using `register_meta`, it should be something like this (untested):

```
meta: {
    external_thumbnail: thumbnail
}
```

**Comment by kadamwhite** [comment] 2017-03-03 16:36
cc @jiji262 / @emreycolakoglu

**Comment by jamesjara** [comment] 2017-05-03 07:33
What about with https://codex.wordpress.org/Function_Reference/update_post_meta  I have a big problem using this plugin and framework... documentations is missing or not working.. hard to debugg, thanks for your help

**Comment by kadamwhite** [comment] 2017-07-11 15:00
Closing this as a duplicate of #280 to unify the threads; meta handling is currently our top-priority documentation issue

**Closed by kadamwhite** 2017-07-11 15:00 UTC
