### ISSUE TITLE
How to properly set a value to meta fields of a custom post type?

### ISSUE THREAD

**Issue by jadebermas** [WP-API/node-wpapi#359] opened 2018-03-20 13:41 UTC
I have a metafields that is assigned to a custom post which I added as a REST API field:

```php
foreach( array( 'field_1', 'field_2' ) as $field ) {
    register_rest_field( $this->post_types,
     $field,
        array(
           'get_callback'    => array( $this, 'get_post_meta' ),
           'update_callback' => array( $this, 'update_post_meta' ),
           'schema'          => null,
         )
    ); 
}
```

And I also have the methods:

```php
public function get_post_meta($object, $field_name, $request) {
    return get_post_meta( $object['id'], $field_name, true );
}

public function update_post_meta($value, $object, $field_name) {
    return update_post_meta( $object->ID, $field_name, $value );
}
```

If I test adding a new post/update and value to `field_1 `and `field_2 `through Postman, it works fine.

But when I try to add a value to the metafields, they don't seem to get added. Here is a snippet of the code I have:

```javascript
response = await this.wordPress.cv_location().create({
      title: article.title,
      content: article.content,
      status: article.status,
      meta: {
        field_1: article.field_1,
        field_2: article.field_2,
      }
    });
```

I notice that if I use ```post()``` instead of ```cv_location()```, the metafields get populated correcrtly with the values but the post gets added to the post post type and not the CV Location post type.

**Comment by kadamwhite** [comment] 2018-12-21 17:57
Are you registering the meta using `register_post_meta( 'your_cpt_name', [] );` on the PHP side? meta needs to be properly registered in order for the `meta` key to work. We need to add a better guide for this to the site, apologies for any confusion.

I know it's been a while but if you're using `register_post_meta` (introduced I believe in WP 4.9.8) and you're still seeing this issue, then please let us know. I'm going to leave it open as a documentation issue for now.

**Comment by kadamwhite** [comment] 2019-01-24 16:18
Closing as a duplicate of #280 — I am be writing a meta handling guide to resolve that ticket which will give an example of this usage as well.

**Closed by kadamwhite** 2019-01-24 16:18 UTC
Labels: Documentation
